BEGIN TRANSACTION;
CREATE TABLE "customer" (
	`name`	VARCHAR(50) PRIMARY KEY UNIQUE,
	`street`	VARCHAR(75) NOT NULL,
	`city`	VARCHAR(50) NOT NULL,
	`state`	VARCHAR(2) NOT NULL,
	`zip`	VARCHAR(5) NOT NULL,
	`interest`	VARCHAR(50) NOT NULL DEFAULT 'somewhat interested',
	`status`	VARCHAR(50) NOT NULL DEFAULT 'nice to have',
	`testimonial`	VARCHAR(300),
	`requested`	VARCHAR(50) NOT NULL DEFAULT 'not requested',
	`isActive` INTEGER NOT NULL DEFAULT 1,
	`robot1` INTEGER NOT NULL DEFAULT 0,
	`robot2` INTEGER NOT NULL DEFAULT 0,
	`robot3` INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE "user" (
	`name` VARCHAR(50) PRIMARY KEY UNIQUE,
	`password` VARCHAR(10) UNIQUE
);
COMMIT;
